### PR TITLE
Block a door with falling rocks when the player overlaps for the first time an specific trigger (functional pass)

### PR DESCRIPTION
**Pull request by agarzonp**
- The trigger will dispatch an event to block the door the first time
the player overlaps it
- There are 3 spawners in the map that will start to spawn rocks when
the event to block the door is fired
- The spawners will stop when a certain amount of rocks has been
spawned. Each rock has a different scale

### CODE REVIEW

**Comment by agarzonp** [comment]
With functional I mean that the rocks are boxes and that it will need some tweaks to get to the desired result.

By the way, it is a known issue that you are able to unblock the path if you start picking the rocks. I am adding this as a bug to the board.

Update: The bug mentioned can be easily resolved by making sure that the rocks are spawned within a blocking volume, plus not allowing to pick up objects that goes beyond a threshold mass. I have just tested this and it works

**Comment by parmandorc** [comment]
Please resolve the conflicts that were introduced when merged #14.

**Comment by agarzonp** [comment]
Done! No changes to the map at all. 

The trap is ready but it will need to be added again into the map.  

I am happy to add the trap to the map again after @oliwiagrambo has merged the new map changes.

In order to test, check the Traps folder and:

1. Add the trigger to the map,
2. Add as many spawners as you want and make sure that they have a reference to the trigger from the details panel.
3. Pass through the trigger and see the boxes spawning.

**Review by parmandorc — APPROVED** [review]
Will merge for now, but we should consider several things to add when there is time.
1) Remove ability to pick up rocks. This would avoid the existent issue that renders the trap useless. However, it would still be highly dependent on how the rocks fall, and thus not deterministic.
2) Adding BlockingVolumes of type InvisibleWall would make it so no matter how the rocks fell, the path is blocked for sure.
3) (Lower priority) Find a way of having the rocks fall without having them spawned in runtime, for performance issues (maybe having them already in the scene and a trap door is opened letting the rocks fall).

**Pull request merged**
